### ISSUE TITLE
Connection issues after saying keyword

### ISSUE THREAD

**Issue by repcop** [DevMiser/DaVinci#11]
Hi DevMiser,
thanks for this excellent work and instructions for use.
I installed everything acc your instructions- and getting the following fail messages, after saying the keyword:

Wake word detected

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

Can you help me please?
BR,
Andreas

**Comment by DevMiser** [comment]
Hi Andreas.  It seems that you are trying to connect to a server that is not reachable. Because the next function called after the wake word is the voice for DaVinci's greeting, I suspect that your RPi is not connecting to the AWS server.  I recommend redoing step 3 on page 6 of the instructions and make certain to use the correct region name (as determined by reviewing the service endpoint information at https://docs.aws.amazon.com/general/latest/gr/rande.html#pol_region).  I hope this helps.  If not, I recommend redoing the AWS IAM and making certain that you enter your AWS access key ID and secret access key correctly.

**Comment by repcop** [comment]
Hi DevMiser, thanks very much, indeed the AWS server was the problem. I changed from eu-central-2 to eu-central-1, and now it works!
