### ISSUE TITLE
Can DaVinci listen other language?

### ISSUE THREAD

**Issue by morimori00** [DevMiser/DaVinci#18]
I want to make DaVinci be able to listen Japanese prompt.
I thought that by changing something in the line below, Davinci could recognize Japanese instead of English. Even after looking at the PicoVoice documentation, I can't find a way to change the language of SpeechToText. Is there any solution?

DaVinci.py line 153
`def listen():

    cobra = pvcobra.create(access_key=pv_access_key)`

**Comment by DevMiser** [comment]
Unfortunately, the language of the speech-to-text cannot be changed at this time. DaVinci uses Picovoice Leopard as its on-device speech-to-text engine.  According to the FAQs on Picovoice's website (https://picovoice.ai/docs/faq/leopard-speech-to-text/): Leopard Speech-to-Text only supports English for now, soon more. Reach out to Picovoice [Sales](https://picovoice.ai/contact/) to tell us about your commercial endeavour if you require support for additional languages. Don’t forget to add the use case, business requirements and project details. Picovoice team will respond to you.

**Comment by morimori00** [comment]
Thank you for answering. I'm going to use whisper api instead. 
But I think this project is cool and I`ll continue to use DaVinci on my RaspberryPi.

**Comment by DevMiser** [comment]
That makes sense.  If you use OpenAI's whisper, you may still want to use Picovoice for wake word and silence detection.  You can train new wake words in Japanese on Picovoice Porcupine (see https://picovoice.ai/platform/porcupine/).  You may also want to use OpenAI's text-to-speech instead of AWS Polly.  I'll post a version of DaVinci that uses that alternative voice engine in the near future.
